// categories/index.js — GENERATED by scripts/gen-categories.mjs. DO NOT EDIT — run `npm run gen:categories`.
// The Palette Categories hub index: one card per category (always bundled) + a lazy loader that
// code-splits each category's PRESETS/VOLUMES into its own chunk, loaded on demand when opened.
export const CATEGORY_INDEX = [
  {"slug":"architecture","category":"Architecture","eyebrow":"Architecture Palette · Sourced from material & light","tagline":"Forty-eight buildings, read for their material, not their blueprint.","count":48,"strip":["#948F88","#958E87","#AEABA6","#7E5F49","#E3E2DF","#DFDEDC","#CBBCA6","#864D3B","#AA8967","#8E8D87","#CFC7B7","#683F32"]},
  {"slug":"brands","category":"Brands","eyebrow":"Brand Palette · Sourced from real identities","tagline":"Seven real brands, read for their actual color — shipped products and researched public identities alike.","count":7,"strip":["#361DF1","#55C9F2","#1F1DF9","#23436E","#EA4F93","#101820","#D62300"]},
  {"slug":"cuisine","category":"Cuisine / Food","eyebrow":"Cuisine Palette · Sourced from ingredient & table","tagline":"Forty-eight dishes, read for their ingredients, not their menu photo.","count":48,"strip":["#DAD8D2","#CBA972","#4F2F22","#DB9A28","#B0C399","#567E51","#CCBC9D","#658E57","#C6A26D","#D8D5CC","#4C3125","#9F7852"]},
  {"slug":"film","category":"Film / Cinema","eyebrow":"Cinema Palette · Sourced from the frame","tagline":"Forty-eight films, read for their colour grade, not their poster.","count":48,"strip":["#9D9891","#E1B53C","#302721","#D5D9DA","#B5231E","#B39366","#273731","#71AA6B","#68766D","#E6A9AA","#C9AE7D","#27292F"]},
  {"slug":"literature","category":"Literature","eyebrow":"Literary Palette · Sourced from setting & page","tagline":"Forty-eight books, read for their colour, not their dust-jacket.","count":48,"strip":["#C49F60","#C6D0D6","#6F9E6A","#A8865B","#7A3F5F","#9E6042","#63676B","#6794C0","#C09B67","#68915A","#B0946E","#817A6F"]},
  {"slug":"music","category":"Music / Genre & Era","eyebrow":"Music Palette · Sourced from scene & sleeve","tagline":"Forty-eight scenes, read for their colour, not their logo.","count":48,"strip":["#265986","#1F1F23","#2B2734","#267C46","#777B80","#E9CA42","#1E2024","#4C698A","#722620","#EB7D2C","#EEBBCB","#AD8048"]},
  {"slug":"nature","category":"Nature / Biomes","eyebrow":"Biome Palette · Sourced from real ecosystems","tagline":"Forty-eight biomes, read for their colour, not their postcard.","count":48,"strip":["#A3A7AC","#CBD3D7","#6EAB67","#9C4333","#B4613C","#305C37","#9E9D58","#BDA46D","#6CBBBB","#AB8958","#1D1D20","#C0492F"]},
  {"slug":"travel","category":"Travel / Territories","eyebrow":"Territory Palette · Sourced from real places","tagline":"Forty-eight territories, read for their colour, not their postcard.","count":48,"strip":["#E3E6E7","#E3E8EC","#C2C4C0","#D8D4CC","#E8EAEC","#3A3A37","#2A3A64","#D4C4A0","#E3D8B8","#D8A888","#3A3E38","#C8C8C4"]}
];

const LOADERS = {
  "architecture": () => import("./architecture.js"),
  "brands": () => import("./brands.js"),
  "cuisine": () => import("./cuisine.js"),
  "film": () => import("./film.js"),
  "literature": () => import("./literature.js"),
  "music": () => import("./music.js"),
  "nature": () => import("./nature.js"),
  "travel": () => import("./travel.js"),
};
// loadCategory(slug) → Promise<{ VOLUMES, PRESETS }>  (null for an unknown slug)
export const loadCategory = (slug) => (LOADERS[slug] ? LOADERS[slug]() : Promise.resolve(null));
