// GENERATED BY REFACTOR (TKT-0023) — relocated verbatim from app.js's former top matter (lines 50-567).
// Pure, DOM-light shared constants/builders used by app.js (core) and every section/overlay mixin file:
// the h() hyperscript, small presentational factories (btn/chip/swatch/switchControl/field), storage-key
// migration + multi-set/profile persistence, the offline license seam, font-loading (self-hosted + lazy
// Google Fonts), app-theme injection, and the per-treatment type specimen copy. No 'this' — safe to import
// from anywhere without creating a cycle back into app.js.
import { appThemeCSS, defaultDocument } from "./model.mjs";
import { STORAGE_KEY, hydrate, serialize } from "./persist.js";
import { clampProfile } from "../engine/flags.js";
import { TYPE_FONTS_CSS } from "./type-fonts.js";


// ── Multi-set storage ─────────────────────────────────────────────────────────
// persist.js owns ONE document's serialize/hydrate. The gallery needs many sets,
// so we keep an index of sets under a sibling key; each set's doc is hydrated
// through persist.hydrate so every field is domain-clamped on load.
export const SETS_KEY = STORAGE_KEY + "-sets";
// The single "source of truth" config slot. In the browser it's a localStorage key; in a Figma
// plugin the config lives IN the file on the document's root pluginData (round-tripped over the bridge).
export const PROJECT_KEY = STORAGE_KEY + "-project";
// The per-MACHINE user profile (item 7, Layer 1) — tier + dev flag overrides. NOT per-doc (a license/tier
// isn't a property of a brand kit), so it lives in its own storage slot alongside sets, never in the doc.
export const PROFILE_KEY = STORAGE_KEY + "-profile";

// The Lemon Squeezy storefront — where a Free user buys a Pro license; the key then activates through the
// web license SEAM (src/main.ts → Lemon Squeezy validate API). An outward LINK only (no network from this
// file, so the offline Figma bundle stays network-free); the Account panel surfaces it in the WEB build only.
// Deep-link to each plan's hosted checkout by VARIANT id (Pro 1849393 · Studio 1849376) — the storefront
// root still lists both, but the CTAs land the buyer straight on the right plan.
export const CHECKOUT_STORE = "https://ultimate-tokens.lemonsqueezy.com";
export const PRO_CHECKOUT_URL = CHECKOUT_STORE + "/checkout/buy/1849393";    // Pro (single-user)
export const STUDIO_CHECKOUT_URL = CHECKOUT_STORE + "/checkout/buy/1849376"; // Studio (teams · 5 seats)

// Outbound links. The product has no domain of its own: support is the repo's issue tracker, the docs are
// the repo README, and billing is Lemon Squeezy's own customer portal. Every one of these RESOLVES today —
// prefer a real link over a branded one that 404s.
export const REPO_URL = "https://github.com/kimgranlund/ultimate-tokens";
export const SUPPORT_URL = REPO_URL + "/issues";
export const DOCS_URL = REPO_URL + "#readme";
export const ACCOUNT_URL = "https://app.lemonsqueezy.com/my-orders";

// Pro-gated export formats (the proExport flag). Free = CSS (css/oklch) + the Figma/JSON interchange; Pro =
// DTCG + the framework configs. flagOf("proExport") is true (unlocked) while TIERS_ENFORCED is off, so these
// only actually gate after go-live. The single-format preview shows an upsell; Download-All omits them.
export const PRO_EXPORT_FORMATS = new Set(["dtcg", "tailwind", "shadcn"]);

// README shipped inside the Download-All zip's experimental figma-aliased/ folder (OD-004).
export const ALIASED_README = `figma-aliased/ — EXPERIMENTAL plugin-free cascade (OD-004)
==========================================================
Same tokens as ../figma/, but the Light/Dark variables carry com.figma.aliasData so they
ALIAS the raw primitives instead of embedding resolved colors — i.e. editing a Color
Primitive cascades to every semantic role, WITHOUT the Ultimate Tokens plugin.

This native-import path is UNVERIFIED end-to-end. The ../figma/ (resolved) files always
import cleanly; the Ultimate Tokens Figma plugin is the reliable cascade. Use this only to test
native import, and import the primitives FIRST.

To test (Figma → Local variables → Import):
  1. Import palette.tokens.json   → creates the "Color Primitives" collection.
  2. Import Light_tokens.json then Dark_tokens.json → creates "Color Semantic".
  3. Open a semantic variable (e.g. primary). It should show as an ALIAS to a
     Color Primitives variable (not a flat color), and editing that primitive should
     update it. If it imports as resolved colors (no alias) or errors on import, the
     cascade did not resolve — use the plugin instead.
`;

// One-time storage-key migration across the FULL rename chain:
//   "hct-palette-state-v1-*"  ->  "nonoun-color-tokens-*"  ->  "ultimate-tokens-*"
// A user last seen on ANY prior prefix keeps their work, so the legacy prefixes are tried
// NEWEST-FIRST (a user who already migrated once must not have older, staler data win).
// Idempotent (only ever fills an ABSENT new key) and tolerates a throwing localStorage
// (the Figma sandboxed iframe) exactly the way save() does.
export const LEGACY_STORAGE_PREFIXES = ["nonoun-color-tokens", "hct-palette-state-v1"]; // newest first
export function migrateStorageKeys() {
  try {
    for (const [suffix, newK] of [["-sets", SETS_KEY], ["-project", PROJECT_KEY], ["-profile", PROFILE_KEY]]) {
      if (localStorage.getItem(newK) != null) continue; // already migrated / already present
      for (const prefix of LEGACY_STORAGE_PREFIXES) {
        const old = localStorage.getItem(prefix + suffix);
        if (old != null) { localStorage.setItem(newK, old); break; } // newest legacy wins
      }
    }
  } catch (e) { /* storage unavailable (sandboxed iframe) — nothing to migrate */ }
}

export function loadSets() {
  let raw = null;
  try {
    raw = JSON.parse(localStorage.getItem(SETS_KEY) || "null");
  } catch {
    raw = null;
  }
  if (!raw || !Array.isArray(raw.sets) || raw.sets.length === 0) {
    // Seed one "Default" set on first run.
    const seed = defaultDocument();
    const id = "set-" + Date.now().toString(36);
    const sets = [{ id, name: "Default", doc: serialize(seed), updated: Date.now() }];
    saveSets(sets);
    return sets;
  }
  return raw.sets;
}

export function saveSets(sets) {
  // A sandboxed iframe (e.g. a Figma plugin UI) blocks localStorage — accessing it
  // throws a SecurityError. Persistence is best-effort: degrade to no-persistence
  // rather than crash the whole app on boot (loadSets's read is guarded too).
  try {
    localStorage.setItem(SETS_KEY, JSON.stringify({ sets }));
  } catch {
    /* no persistence available — run in-memory */
  }
}

// loadProfile/saveProfile — the per-machine profile, best-effort like sets (a sandboxed Figma iframe blocks
// localStorage). clampProfile sanitizes whatever was stored; a fresh machine → { tier:"free" }.
export function loadProfile() {
  let raw = null;
  try { raw = JSON.parse(localStorage.getItem(PROFILE_KEY) || "null"); } catch { raw = null; }
  return clampProfile(raw);
}
export function saveProfile(profile) {
  try { localStorage.setItem(PROFILE_KEY, JSON.stringify(clampProfile(profile))); } catch { /* in-memory */ }
}

// defaultLicenseService — the OFFLINE default for the pluggable license SEAM (this._licenseService), item 7.
// PURE + OFFLINE (no network): a dev/QA "manual entitlement" path so activate/validate/deactivate + the tier
// flip + seat handling are real and testable without a server. A key shaped "PRO-XXXX" activates (a fake
// instance id + an active entitlement); anything else is a friendly rejection. The WEB build (src/main.ts)
// REPLACES this with a Lemon-Squeezy-backed service that talks to the public License API — those fetches are
// WEB-ONLY and deliberately NOT written in this file, so app.js (and the offline Figma plugin bundle it
// becomes, manifest networkAccess:"none") stays network-free. Methods may be async (the web ones are);
// enterLicense/clearLicense await them. activate→{ ok, entitlement?, instanceId?, error? }; deactivate→{ ok }.
export const PRO_KEY_RE = /^PRO-[A-Za-z0-9]{4,}(?:-[A-Za-z0-9]+)*$/;
export const defaultLicenseService = {
  activate(key) {
    const k = String(key || "").trim();
    if (PRO_KEY_RE.test(k)) return { ok: true, entitlement: { status: "active" }, instanceId: "dev-" + k.slice(-4) };
    return { ok: false, error: "We couldn't validate that license key. Check it and try again." };
  },
  validate(key) {
    const k = String(key || "").trim();
    if (PRO_KEY_RE.test(k)) return { ok: true, entitlement: { status: "active" } };
    return { ok: false, error: "We couldn't validate that license key. Check it and try again." };
  },
  deactivate() { return { ok: true }; },
};

// A human-readable label for this device's activation INSTANCE (shown in the Lemon-Squeezy dashboard; the
// returned instance id is what actually holds the seat). Best-effort — platform if the UA exposes it.
export function licenseInstanceName() {
  let plat = "web";
  try { plat = (typeof navigator !== "undefined" && navigator.platform) || "web"; } catch { /* no navigator */ }
  return "Ultimate Tokens · " + plat;
}

// The boolean capability flags exposed as dev/QA override toggles in Settings › Account (maxSets is VALUED,
// so it's not a toggle). Each writes profile.flagOverrides via setProfile — handy for exercising a gate.
export const DEV_FLAG_TOGGLES = [
  { key: "proExport", label: "Pro export formats", desc: "Force the Pro-only export formats on or off." },
  { key: "advancedTreatments", label: "Advanced treatments", desc: "Force the advanced type/geometry treatments." },
  { key: "hostedMcp", label: "Hosted MCP", desc: "Force the hosted Brand-Kit MCP capability." },
];

export function newSet(name) {
  const doc = serialize(defaultDocument());
  return { id: "set-" + Math.random().toString(36).slice(2, 9), name, doc, updated: Date.now() };
}

// hydrateStoredDoc — hydrate a doc read from PERSISTENT storage (a saved set record). The OKLCH-native
// default flip means an ABSENT hueSpace now hydrates to "oklch" — correct for a brand-new doc, but a
// STORED set that predates the hueSpace field was authored under cam16 and must KEEP rendering in cam16.
// So we stamp "cam16" on a stored doc that lacks the field BEFORE hydrate (legacy preservation). A doc
// saved with hueSpace already set (every doc since the field landed) round-trips through untouched.
export function hydrateStoredDoc(stored) {
  const d = stored && typeof stored === "object" && stored.hueSpace == null ? { ...stored, hueSpace: "cam16" } : stored;
  return hydrate(d);
}

// ── app-theme injection (dogfooding) ────────────────────────────────────────────
// The chrome themes itself with the tokens the tool generates. On boot we run the
// tool's own `exportCSS` over the FIXED 8 default palettes (appThemeCSS) and inject
// the result once as <style id="ultimate-tokens-theme"> into <head>, so every --c-* role and
// raw var is available globally for styles.css to consume. We use the FIXED default
// set (not the user's edited doc) so the chrome stays stable while a doc is edited.
export const APP_THEME_STYLE_ID = "ultimate-tokens-theme";
export function ensureAppTheme() {
  if (typeof document === "undefined" || !document.head) return;
  if (document.getElementById(APP_THEME_STYLE_ID)) return; // inject exactly once
  const style = document.createElement("style");
  style.id = APP_THEME_STYLE_ID;
  style.textContent = appThemeCSS();
  document.head.appendChild(style);
}

// ── typography web fonts (lazy) ─────────────────────────────────────────────────
// FONT LOADING runs in two tiers.
// TIER 1 — SELF-HOSTED (always): the five base treatments name four free Google Fonts — Inter, Inter Tight
// (geometric sans), Source Serif 4 (high-contrast serif), JetBrains Mono. Their Latin subset is inlined as
// base64 @font-face (src/ui/type-fonts.js, ~230KB), injected lazily (ensureTypeFonts, first Typography open).
// `data:` URIs are inline, not network requests, so these render EVERYWHERE — online, offline, and inside
// the Figma plugin (manifest networkAccess:"none", where any CDN is hard-blocked): offline-proof, privacy-
// clean, store-compliant.
// TIER 2 — WEB-APP ONLY (lazy CDN): per-palette typography draws on ~200 further faces, far too heavy to
// embed. In the WEB app they are lazy-loaded from the Google Fonts CSS API on demand (ensureWebFonts) so the
// live specimen renders the REAL face when you click between palette families. This tier IS a runtime CDN
// request, so it is GATED OFF in the Figma plugin (this.inFigma) — there (and offline) an unbundled face
// falls back to the generic. Every EXPORT carries the real family name regardless of what the preview loads.
export const TYPE_FONTS_LINK_ID = "ultimate-tokens-type-fonts";
export function ensureTypeFonts() {
  if (typeof document === "undefined" || !document.head) return;
  if (document.getElementById(TYPE_FONTS_LINK_ID)) return; // inject exactly once
  // Inject the declarative @font-face <style> (the CSS path) …
  const style = document.createElement("style");
  style.id = TYPE_FONTS_LINK_ID;
  style.textContent = TYPE_FONTS_CSS;
  document.head.appendChild(style);
  // … AND eagerly register + load each face via the FontFace API. The <style> @font-face path is LAZY —
  // Chromium only activates a face the first time an element uses it, so a font not in the current
  // treatment (e.g. Source Serif 4 while on a sans treatment) stays inactive and its first use flashes the
  // fallback. document.fonts.add + load() activates ALL four up front (data: URIs, so still offline-safe).
  if (document.fonts && typeof FontFace === "function") {
    for (const m of TYPE_FONTS_CSS.matchAll(/font-family:'([^']+)';font-style:normal;font-weight:([^;]+);font-display:swap;src:url\((data:[^)]+)\)/g)) {
      try {
        const ff = new FontFace(m[1], `url(${m[3]})`, { weight: m[2].trim(), style: "normal", display: "swap" });
        document.fonts.add(ff);
        ff.load().catch(() => { /* offline/blocked — the generic fallback holds */ });
      } catch { /* ignore a malformed face */ }
    }
  }
}

// ensureWebFonts (TIER 2, web-app only) — lazily load the per-palette faces that are NOT self-hosted from
// the Google Fonts CSS API, one <link> per family (idempotent by id). GATED OFF in the Figma plugin
// (networkAccess:"none") — call with this.inFigma. A family's config weight is served by requesting the full
// variable range; a static/single-master face 400s that request, so we retry the default instance (the
// typeface still renders; the browser synthesises the weight). A non-Google family 404s harmlessly and the
// generic fallback holds.
export const SELF_HOSTED_FONTS = new Set(["Inter", "Inter Tight", "Source Serif 4", "JetBrains Mono"]);
export const GENERIC_FONTS = new Set(["serif", "sans-serif", "monospace", "system-ui", "ui-serif", "ui-sans-serif", "ui-monospace", "cursive", "fantasy", "inherit", "initial", "—"]);
export function ensureWebFont(fam) {
  const id = "ultimate-tokens-wf-" + fam.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  if (document.getElementById(id)) return; // load each family exactly once
  const base = "https://fonts.googleapis.com/css2?family=" + encodeURIComponent(fam).replace(/%20/g, "+");
  const add = (href, onFail) => {
    const link = document.createElement("link");
    link.id = id; link.rel = "stylesheet"; link.href = href;
    if (onFail) link.onerror = () => { link.remove(); onFail(); };
    document.head.appendChild(link);
  };
  add(base + ":wght@100..900&display=swap", () => add(base + "&display=swap")); // full range → default instance on 400
}
export function ensureWebFontPreconnect() {
  if (document.getElementById("ultimate-tokens-wf-pc-gstatic")) return; // once (gstatic is appended last)
  for (const [host, id, cors] of [["https://fonts.googleapis.com", "ultimate-tokens-wf-pc-gapis", false], ["https://fonts.gstatic.com", "ultimate-tokens-wf-pc-gstatic", true]]) {
    const l = document.createElement("link"); // preconnect links must be direct <head> children
    l.id = id; l.rel = "preconnect"; l.href = host;
    if (cors) l.crossOrigin = "anonymous";
    document.head.appendChild(l);
  }
}
export function ensureWebFonts(fonts, inFigma) {
  if (inFigma) return; // TIER 2 is web-app only — the Figma plugin stays on the self-hosted subset
  if (typeof document === "undefined" || !document.head || !document.createElement) return;
  const need = Object.values(fonts || {})
    .map((r) => (r || "").trim())
    .filter((fam) => fam && !SELF_HOSTED_FONTS.has(fam) && !GENERIC_FONTS.has(fam.toLowerCase()));
  if (!need.length) return; // a purely self-hosted config makes ZERO CDN contact (not even a preconnect)
  ensureWebFontPreconnect(); // warm the Google Fonts connections only when we're actually loading a face
  for (const fam of need) ensureWebFont(fam);
}

// setColorScheme — flip the document's color-scheme so EVERY light-dark() token —
// the generated --c-* chrome tokens included — resolves to the chosen mode. "system" maps to
// "light dark" so the browser follows the OS prefers-color-scheme.
export function setColorScheme(theme) {
  if (typeof document === "undefined") return;
  const root = document.documentElement;
  if (root) root.style.colorScheme = theme === "system" ? "light dark" : theme; // "light" | "dark" | "light dark"
}

// ── tiny helpers ───────────────────────────────────────────────────────────────
export const h = (tag, attrs = {}, ...kids) => {
  const el = document.createElement(tag);
  for (const [k, v] of Object.entries(attrs)) {
    if (v == null || v === false) continue;
    if (k === "class") el.className = v;
    else if (k === "html") el.innerHTML = v;
    else if (k.startsWith("on") && typeof v === "function") el.addEventListener(k.slice(2), v);
    else if (k === "style") el.setAttribute("style", v);
    else el.setAttribute(k, v === true ? "" : v);
  }
  for (const kid of kids.flat()) {
    if (kid == null || kid === false) continue;
    el.append(kid.nodeType ? kid : document.createTextNode(String(kid)));
  }
  return el;
};
export const fmt = (x, d = 0) => Number(x).toFixed(d);
export const ago = (ts) => {
  const s = (Date.now() - ts) / 1000;
  if (s < 60) return "just now";
  if (s < 3600) return Math.floor(s / 60) + "m ago";
  if (s < 86400) return Math.floor(s / 3600) + "h ago";
  return Math.floor(s / 86400) + "d ago";
};

export const CURVES = ["linear", "sine", "cubic", "logistic", "exp"];

// Damping presets — named one-click setups for the four differential-damping knobs
// (damp · dampCurve · dampAmp · dampBias), so the curve is discoverable without
// hand-tuning. "Default" is the legacy edge-damp (backward-compatible).
export const DAMP_PRESETS = [
  { name: "Default", damp: 80, dampCurve: 1.5, dampAmp: 0, dampBias: 0 },
  { name: "Calm ends", damp: 92, dampCurve: 2.6, dampAmp: 0, dampBias: 0 },
  { name: "Vivid mids", damp: 70, dampCurve: 1.5, dampAmp: 55, dampBias: 0 },
  { name: "Shade-heavy", damp: 84, dampCurve: 1.5, dampAmp: 12, dampBias: 55 },
  { name: "Tint-heavy", damp: 84, dampCurve: 1.5, dampAmp: 12, dampBias: -55 },
  { name: "Flat", damp: 35, dampCurve: 1, dampAmp: 0, dampBias: 0 },
];

// ── primitive factories ─────────────────────────────────────────────────────────
// Small, presentational builders shared across the render methods so a control's
// contract (markup + a11y) lives in ONE place instead of being re-typed inline.
// Pure builders take their handlers as arguments and live here; the one stateful,
// focus-managing control (segmented) is a class method below (it needs `this` to
// re-focus after a render). See docs/reference/references/component-inventory.md.

// switchControl — an accessible on/off (or either/or) switch. Replaces the old
// `<div class=toggle onclick>` which had no role, no tab focus, and no keyboard. A
// real <button role=switch> gets :focus-visible + Enter/Space toggling from the
// platform; aria-checked carries the state to assistive tech. `label` is the visible
// value (Enabled / oklch / gamut …); `ariaLabel` is the stable purpose, since the
// sibling <label> (when present) is not programmatically associated.
export const switchControl = ({ on, onToggle, label, ariaLabel }) =>
  h(
    "button",
    {
      type: "button",
      class: "toggle" + (on ? " on" : ""),
      role: "switch",
      "aria-checked": on ? "true" : "false",
      "aria-label": ariaLabel,
      onclick: onToggle,
    },
    h("span", { class: "track", "aria-hidden": "true" }),
    h("span", { class: "toggle-label" }, label),
  );

// swatch — a fixed-size color chip, the single source for the app's many little color
// squares (inspector dot, role refs, …). `alpha:true` lays the fill over the shared
// checkerboard (.swatch.alpha, defined once in CSS) so translucent colors read as
// translucent. `size` drives the --sw custom property; decorative, so aria-hidden.
export const swatch = (hex, { size = 16, alpha = false, cls = "", title, onClick } = {}) =>
  h(
    "span",
    {
      class: "swatch" + (alpha ? " alpha" : "") + (cls ? " " + cls : "") + (onClick ? " swatch-btn" : ""),
      style: `--sw:${size}px` + (alpha ? "" : `;background:${hex}`),
      title,
      // opt-in interactive (e.g. the Roles inspector click-to-copy): a keyboard-accessible role=button.
      ...(onClick
        ? { role: "button", tabindex: "0", "aria-label": title || `Copy ${hex}`,
            onclick: onClick,
            onkeydown: (e) => { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); onClick(e); } } }
        : { "aria-hidden": "true" }),
    },
    alpha ? h("span", { class: "swatch-fill", style: `background:${hex}` }) : false,
  );

// btn — the app's button with a small, orthogonal variant vocabulary: ghost (default,
// bordered), primary (accent fill), danger (ghost + danger hover), bare (no chrome — for
// buttons that bring their own, e.g. copy-float / map-reset). Anything position- or
// layout-specific (add-pal-btn, figma-plugin-btn, …) is an extra `cls`, NOT a variant —
// that separation is the whole point (it un-pollutes the variant axis). Icon-only buttons
// MUST pass `ariaLabel`. `children` is a node or an array of nodes.
export const BTN_VARIANT = { ghost: "ghost", primary: "primary", danger: "ghost danger", bare: "" };
export const btn = (children, { variant = "ghost", cls = "", title, ariaLabel, ariaPressed, onclick, type = "button", disabled } = {}) =>
  h(
    "button",
    {
      type,
      class: [BTN_VARIANT[variant] ?? "ghost", cls].filter(Boolean).join(" "),
      title,
      "aria-label": ariaLabel,
      "aria-pressed": ariaPressed,
      disabled: disabled ? true : undefined,
      onclick,
    },
    ...(Array.isArray(children) ? children : [children]),
  );

// color-scheme toggles (app chrome + canvas preview): a 3-state cycle rendered icon-only.
// sun = light, moon = dark, the split-circle "theme" glyph = system (follow the OS).
export const SCHEME_ICON = { system: "theme", light: "sun", dark: "moon" };
export const SCHEME_NEXT = { system: "light", light: "dark", dark: "system" };

// CANVAS_INSET — the fixed px offset fit() positions the canvas-scene's top-left corner at from
// canvas-area's top-left, on reset/section-switch/dblclick (Color · Typography · Geometry alike).
// Replaces the old dead-center default so the content's own top-left is what's visible first.
export const CANVAS_INSET = 32;

// Per-treatment specimen copy — each treatment carries BESPOKE placeholder text aligned to its concept
// (lifestyle app · luxury maison · long-form journalism · ops dashboard · gig poster), so the type
// previews read like the world they're for instead of one shared sports demo. `para` is the Body-LG
// long-form filler (2026-07-13: every voice is now a fixed 3-step SM/MD/LG ramp, LG is Body's largest
// step, replacing the old Body-XL). Sub-heading/Kicker render uppercase via the engine's textTransform;
// strings stay title-case here (except Brutalist's already-shouting label line). Voice taxonomy renamed
// 2026-07-13: Heading→Headline, UI→Label; Quote folded into Lead, Legal folded into Body, Caption's copy
// moved to the new Tiny voice; Title/Sub-title are new.
export const TYPE_SPECIMENS = {
  product: {
    "Display": "Make today count",
    "Headline": "Your week, at a glance",
    "Sub-heading": "This Morning",
    "Title": "This week's habits",
    "Sub-title": "Updated 2m ago",
    "Body": "A calmer way to plan your day. Set the intentions that matter, check off what you finish, and let the small stuff go.",
    "Lead": "The small stuff has a way of piling up. Here's a calmer place to set it down and start the day with a clear head.",
    "Label": "Today · 4 of 6 done · 2 left",
    "Body-mono": "GET /v1/habits/today → 200",
    "Label-mono": "v2.4.1 · build 1197",
    "Kicker": "Daily Brief",
    "Tiny": "Your streak keeps itself — no daily check-in required.",
    "Tiny-mono": "sha256:a1b2c3d4 verified locally.",
    "UI-control": "Add habit",
    "UI-widget": "4 left",
    para: "A calmer way to plan your day. Set the intentions that matter, check off what you finish, and let the small stuff go — your streak keeps itself, so you can stay present for the part that actually counts.",
  },
  luxury: {
    "Display": "The Maison Collection",
    "Headline": "An invitation to slow down",
    "Sub-heading": "The Atelier",
    "Title": "Autumn Selections",
    "Sub-title": "Est. 1998",
    "Body": "Crafted in limited number, each piece is finished by hand in our atelier and made to be kept for a lifetime.",
    "Lead": "A collection made in limited number, for those who measure luxury in decades rather than seasons.",
    "Label": "Reserve · Suite 9 · 2 nights",
    "Body-mono": "RES · 2026-09-14 · SUITE-09",
    "Label-mono": "REF 09-14 · LOT 003",
    "Kicker": "Private Reserve",
    "Tiny": "Finished entirely by hand in the atelier, Florence.",
    "Tiny-mono": "Serial no. MB-2026-0417.",
    "UI-control": "Request an appointment",
    "UI-widget": "New",
    para: "Crafted in limited number and finished entirely by hand, every piece leaves our atelier with the quiet confidence of something built to outlast its season — and to be passed, one day, to someone you love.",
  },
  editorial: {
    "Display": "The long road back",
    "Headline": "Notes from a vanishing coastline",
    "Sub-heading": "Field Report",
    "Title": "The vanishing coastline",
    "Sub-title": "Vol. 12 · No. 47",
    "Body": "For thirty years she walked these shores at dawn. What she saw — and what she could no longer find — became the story.",
    "Lead": "For thirty years she walked the shore at dawn — until the birds she counted began, quietly, to disappear.",
    "Label": "Issue 47 · 12 min read · Share",
    "Body-mono": "By J. Okonkwo · Oct 2026",
    "Label-mono": "ISSN 2049-3630 · No. 47",
    "Kicker": "Dispatch",
    "Tiny": "Above: the north cove at first light, September.",
    "Tiny-mono": "Archived at doi.org/10.1234/vc47.",
    "UI-control": "Read the story",
    "UI-widget": "12 min",
    para: "For thirty years she walked these shores at dawn, counting the birds the way her mother had taught her. What she saw over those decades, and what she slowly stopped finding, is the story we set out to tell.",
  },
  technical: {
    "Display": "99.98% uptime",
    "Headline": "Cluster health overview",
    "Sub-heading": "Live Metrics",
    "Title": "Region-by-region breakdown",
    "Sub-title": "us-east-1 · v2.4.1",
    "Body": "All regions reporting nominal. Latency held under 80ms across the last 24 hours of production traffic.",
    "Lead": "Every region reporting nominal — a look at the last 24 hours of production traffic, node by node.",
    "Label": "p99 78ms · 1.2k rps · 0 err",
    "Body-mono": "$ kubectl get pods -n prod",
    "Label-mono": "v2.4.1 · commit 9f3a21c",
    "Kicker": "System Status",
    "Tiny": "Fig. 3 — p99 latency, rolling 24-hour window.",
    "Tiny-mono": "trace-id: 7e2f9a1c-40b2-4e91.",
    "UI-control": "Acknowledge all",
    "UI-widget": "OK",
    para: "All regions are reporting nominal: latency held under 80ms across the last 24 hours, the error budget is untouched for the quarter, and the autoscaler released eleven nodes overnight without a single dropped request.",
  },
  statement: {
    "Display": "After Hours",
    "Headline": "Three nights only",
    "Sub-heading": "Main Stage",
    "Title": "Main stage lineup",
    "Sub-title": "18+ · GA + VIP",
    "Body": "No openers. No encore. One set, start to finish, loud enough to feel in your chest.",
    "Lead": "One set, start to finish, three nights only — loud enough to feel in your chest and gone before the city wakes.",
    "Label": "SOLD OUT · WAITLIST OPEN",
    "Body-mono": "FRI 02 · WAREHOUSE 9 · DTLA",
    "Label-mono": "TICKET #04821 · GA",
    "Kicker": "Doors 9PM",
    "Tiny": "Warehouse 9, DTLA — doors at nine.",
    "Tiny-mono": "Presented by NOCTURNE — est. 2019.",
    "UI-control": "Get tickets",
    "UI-widget": "Sold out",
    para: "No openers, no encore, no second chances: one set from start to finish, three nights only, loud enough to feel in your chest and gone before the city wakes up. Doors at nine — don't be the one telling it secondhand.",
  },
};
export const TYPE_SAMPLE = (cat, t = "product") => (TYPE_SPECIMENS[t] || TYPE_SPECIMENS.product)[cat] || "The quick brown fox";
export const TYPE_PARA = (t = "product") => (TYPE_SPECIMENS[t] || TYPE_SPECIMENS.product).para;

// chip — a small pill. mode "interactive" (a <button>, `on` = active/pressed) or "status"
// (a non-interactive <span> badge, optional `tone`). Folds the in-flow pill stylings
// (damp-presets, map-drift-sum) onto one .chip primitive. The absolutely-positioned
// tile-tag overlay badge stays separate — it is an overlay, not an in-flow chip.
export const chip = (label, { mode = "status", on = false, tone = "", cls = "", title, onclick } = {}) => {
  const klass = ["chip", on ? "on" : "", tone, cls].filter(Boolean).join(" ");
  return mode === "interactive"
    ? h("button", { type: "button", class: klass, "aria-pressed": on ? "true" : "false", title, onclick }, label)
    : h("span", { class: klass, title }, label);
};

// the common responsive breakpoint widths offered as one-click quick-picks beside the breakpoint-mode
// min-width field (Phase 2 — chips, not a native <datalist>: the app owns its UI + Safari's datalist on
// number inputs is unreliable). The number field stays for any custom width.
export const MODE_WIDTH_PRESETS = [476, 768, 992, 1280, 1540];

// field — a labeled control row. ASSOCIATES the <label> with the control (label[for] +
// control[id]) so the visible label IS the control's accessible name and clicking it
// focuses the control — the association the inline .field rows lacked (Name / Distribution
// / Curve were screen-reader-nameless). The caller builds the control; field() stamps the
// id and a fallback aria-label (left intact if the control already carries one, e.g. a
// switchControl). NB: sliders carry their own label+readout, so they are not field()s.
export const field = (labelText, control, { labelTitle } = {}) => {
  const id = "fld-" + String(labelText).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  if (control && control.setAttribute) {
    control.setAttribute("id", id);
    if (!control.getAttribute("aria-label")) control.setAttribute("aria-label", labelText);
  }
  return h("div", { class: "field" }, h("label", { for: id, title: labelTitle }, labelText), control);
};
